version: '3.7'
services:
  chain:
    container_name: goerli_test_chain
    image: openethereum/openethereum
    volumes:
      - ./:/home/openethereum/.local/share/openethereum
    command: >
      --config /home/openethereum/.local/share/openethereum/goerli-config.toml
      --base-path /home/openethereum/.local/share/openethereum/goerli-data
      --ports-shift 2
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303/udp
