version: '3.7'
services:
  chain:
    container_name: crossChainContracts_test_chain
    image: openethereum/openethereum
    volumes:
      - ./:/home/openethereum/.local/share/openethereum
    command: >
      --config /home/openethereum/.local/share/openethereum/config.toml
      --base-path /home/openethereum/.local/share/openethereum/chain-data
      --keys-path /home/openethereum/.local/share/openethereum/keys
      --ports-shift 2
    ports:
      - 8547:8547
      - 8548:8548
      - 30303:30303
      - 30303:30303/udp
